### ISSUE TITLE
Flatpak version of Baobab shows less files

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.baobab#11]
Hi, I have installed Baobab from flatpak also from Ubuntu 22.04 repos.

The fist one is from Ubuntu 22.04 repos (Baobab 41)
![normal](https://user-images.githubusercontent.com/6218679/170961273-2ee2dcfc-bf69-4beb-8af8-5937a6d3a53e.png)

The second one from Flatpak via flathub repos (Baobab 42)
![flatpak](https://user-images.githubusercontent.com/6218679/170961283-fe569f9d-40f4-498d-9ad8-ae935e4c8afd.png)

filesystem=host permission was given default. I didn't touch any permission.

It this a flatpak limitation?

**Comment by bilelmoussaoui** [comment]
Yes it is, even if you give the app host permission, it can't access all the files as some directories are in a "disallow" list and can never be accessed

**Comment by MateusRodCosta** [comment]
~~Please add `~/.var/app:ro` to filesystem permissions.~~

Nevermind, #10 is already dealing with this.

**Comment by ghost** [comment]
Thanks.
